<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>e</string>
		<string>e100</string>
		<string>easm</string>
	</array>
	<key>name</key>
	<string>E100 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comments (single line)</string>
			<key>match</key>
			<string>^\s*//.*\n?$</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>preprocessor directive(s)</string>
			<key>match</key>
			<string>^(#include)\s+(\w*\.(?:e|e100|easm))\s*\n?$</string>
			<key>name</key>
			<string>meta.preprocessor</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>.data statements</string>
			<key>match</key>
			<string>(^\w+)\s+(\.data)\s+(0[xX][\da-fA-F]+|\d+)(?:\s*|(?:\s+(\w*)))(?:\s*|(?:\s+(.*)))\n?$</string>
			<key>name</key>
			<string>meta.variable</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>halt statement (no arguments)</string>
			<key>match</key>
			<string>(^\w*)\s+(halt)(?:(?:\s+(\w*\s*\w*\s*\w*))|\s*)(?:\s*|(?:\s+(.*)))\n?$</string>
			<key>name</key>
			<string>meta.statement</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ret statemnt (one argument)</string>
			<key>match</key>
			<string>(^\w*)\s+(ret)\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w+))(?:(?:\s+(\w*\s*\w*))|\s*)(?:\s*|(?:\s+(.*)))\n?$</string>
			<key>name</key>
			<string>meta.statement</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>two-argument opcode statements</string>
			<key>match</key>
			<string>(^\w*)\s+(call|cp|not)\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w*))\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w*))(?:(?:\s+(\w*))|\s*)(?:\s*|(?:\s+(.*)))\n?$</string>
			<key>name</key>
			<string>meta.statement</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>three-argument opcode statements</string>
			<key>match</key>
			<string>(^\w*)\s+(add|sub|mult|div|and|or|sl|sr|cpfa|cpta|be|bne|blt)\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w*))\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w*))\s+(?:(0[xX][\da-fA-F]+|\d+)|(\d+\w+)|([^\d]\w*))(?:\s*|(?:\s+(.*)))\n?$</string>
			<key>name</key>
			<string>meta.statement</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.easm</string>
	<key>uuid</key>
	<string>2ab58527-fa06-43ab-ba1c-adee8c7bb7d1</string>
</dict>
</plist>
